"""Independent CSPICE checks for the SPK range reader and browser Kepler fixtures."""
import json
import struct
import tempfile
from pathlib import Path
import numpy as np
import spiceypy as spice
from resources import WEB, digest
from spk import RemoteSPK

manifest = json.loads((WEB / "src/extended-data.json").read_text())
count = 0
for info in manifest["spk"]:
    kernel = RemoteSPK(info["url"])
    for body in manifest["bodies"].values():
        target = body.get("naif")
        if target is None: continue
        et = body["stateEpochET"]
        candidates = [s for s in kernel.segments if s[2] == target and s[0] <= et <= s[1]]
        if not candidates: continue
        segment = candidates[-1]
        _, _, _, center, frame, kind, address, final = segment
        initial, interval, size, n = struct.unpack(kernel.order + "4d", kernel.read((final - 4) * 8, 32))
        index = min(int((et - initial) // interval), int(n) - 1)
        data = np.frombuffer(kernel.read((address - 1 + index * int(size)) * 8, int(size) * 8), dtype=kernel.order + "f8")
        midpoint, span = data[:2]
        degree = (int(size) - 2) // (3 if kind == 2 else 6) - 1
        with tempfile.TemporaryDirectory(prefix="solarspace-spk-check-") as temporary:
            filename = str(Path(temporary) / "record.bsp")
            handle = spice.spkopn(filename, "OpenSpace record verification", 0)
            writer = spice.spkw02 if kind == 2 else spice.spkw03
            writer(handle, target, center, "J2000" if frame == 1 else "ECLIPJ2000", midpoint - span, midpoint + span, "original Chebyshev record", interval, 1, degree, data[2:].copy(), midpoint - span)
            spice.spkcls(handle)
            spice.furnsh(filename)
            for time in [et, midpoint - span * .7, midpoint + span * .7]:
                expected, _ = spice.spkgeo(target, time, "ECLIPJ2000", center)
                actual, _ = kernel.state(target, time)
                assert np.max(np.abs(actual[:3] - expected[:3])) < 1e-6
                assert np.max(np.abs(actual[3:] - expected[3:])) < 1e-10
            spice.kclear()
        count += 1

fixtures = []
for id in ["phobos", "titan", "triton", "nereid", "charon", "eris", "sedna", "ceres"]:
    orbit = manifest["bodies"][id]["orbit"]
    a = orbit["a"] * 149597870.7
    mu = (2 * np.pi / (orbit["period"] * 86400)) ** 2 * a ** 3
    elements = [a * (1 - orbit["e"]), orbit["e"], *np.deg2rad([orbit["i"], orbit["node"], orbit["peri"], orbit["m"]]), 0, mu]
    for fraction in [-.4, 0, .23]:
        seconds = orbit["period"] * 86400 * fraction
        state = spice.conics(elements, seconds)
        fixtures.append({"id": id, "orbit": orbit, "time": orbit["epoch"] + seconds * 1000, "sceneAU": [state[0] / 149597870.7, state[2] / 149597870.7, -state[1] / 149597870.7]})
folder = WEB / "tests/fixtures"
folder.mkdir(exist_ok=True)
(folder / "kepler-reference.json").write_text(json.dumps({"source": "NAIF CSPICE conics, generated by scripts/verify-system.py", "fixtures": fixtures}, indent=2) + "\n")
for resource in manifest["resources"]:
    if "output" in resource:
        assert digest(WEB / "public" / resource["output"]) == resource["outputSha256"]
print(f"Verified {count} SPK segments against native CSPICE at three times each, {len(fixtures)} browser reference states, and all imported image/model hashes.")
